//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfeErsozlu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiRegistration
    {
        public int ApiId { get; set; }
        public string ApiKey { get; set; }
        public string TcNo { get; set; }
        public int Permission { get; set; }
        public string FullName { get; set; }
    }
}
