//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfeErsozlu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int BasketId { get; set; }
        public System.DateTime BarketDate { get; set; }
        public bool BasketOkay { get; set; }
        public int BasketProductNumber { get; set; }
        public decimal BasketTotalPrice { get; set; }
        public int BasketProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
